markdown: kramdown
permalink: /:title/
url: http://www.x3553x.com/
name: x3553x
author: x3553x
qq: 1659998702
email: xjc_sun@163.com
duoshuo: x3553x
weibo: 隐藏
github: xiaojc
safe: true
paginate: 20
about: "这里是 x3553x 的个人博客，创建于 2017 年。"
